### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by AliMickey** [luluhoc/home-cinema-toolkit#1]
Using the following docker compose file (same as example in readme): 

`hct:
    container_name: hct
    image: lulu45/home-cinema-toolkit:beta
    restart: unless-stopped
    networks: 
      - home
    ports:
      - 12400:12400`

I get the following error
![image](https://user-images.githubusercontent.com/60691199/90354020-49b69580-e08b-11ea-8e26-4075d2b83244.png)

**Comment by luluhoc** [comment]
The docker image should work now.

**Comment by AliMickey** [comment]
![image](https://user-images.githubusercontent.com/60691199/90396966-7b0a8200-e0da-11ea-80b2-10f4c56827d7.png)

It does work however the layout does not match your screenshot in readme.

**Comment by luluhoc** [comment]
There must be a problem with some css framework I will repair it later.

**Comment by luluhoc** [comment]
Can you try if it is working now?

**Comment by AliMickey** [comment]
Yep it looks good now. 

Aside from this, is OMDB used only for the poster? If so can you make it so we can run the search without an API key for it.

**Comment by AliMickey** [comment]
However searching does not work, 

![image](https://user-images.githubusercontent.com/60691199/90453577-59d67f80-e134-11ea-861a-4e650c6617b9.png)


I have tried multiple times and made sure the api key is correct (works through browser).

**Comment by luluhoc** [comment]
API key to OMDB right? The key must be wrong. I have the premium key and it works. Try the key `thewdb`.

**Comment by AliMickey** [comment]
My key is `14ac3625`

Yours did work after waiting for a bit, perhaps add a loading icon. I thought it failed at first before checking logs.

Using mine it gets stuck at "Waiting for OMDB"

**Comment by luluhoc** [comment]
There should be loading icon. I will change the interface soon.

**Comment by AliMickey** [comment]
Fair enough, thats good. 

Could you try my key please?

**Comment by luluhoc** [comment]
It is free key right?

**Comment by AliMickey** [comment]
yep the one with 1000 daily limit.

**Comment by luluhoc** [comment]
![image](https://user-images.githubusercontent.com/22813220/90497052-eb4eed00-e146-11ea-9313-2e58e216a0fe.png)

**Comment by luluhoc** [comment]
I created the new key and even in browser it gives me invalid API key, I think that there is a problem with free keys.

**Comment by AliMickey** [comment]
Oh i was using the supplied [link](https://www.omdbapi.com/?i=tt3896198&apikey=14ac3625)in the verification email which seems to be not affected by the limit. 

Thanks for the help.
