### ISSUE TITLE
Deleted movies reappearing in search results

### ISSUE THREAD

**Issue by kjac3585** [luluhoc/home-cinema-toolkit#10]
Movies are reappearing in HCT after being deleted, even though radarr shows it as being removed. This results in HCT throwing up a "deleting" server error when selecting a movie for deletion that has already been removed from radarr. This seems to happen only when HCT refreshes the page after deleting X amount of movies. It does not seem to happen when executing a new search as the deleted movies are then removed from the list.

**Comment by luluhoc** [comment]
Can you try if it does the same? I couldn't replicate the issue, I have added storing imdb ratings for one month btw :) Wait for the docker hub to build of course. Please star the repo if you can :)

**Comment by luluhoc** [comment]
Docker image is built please let me know if it works for you :)

**Comment by kjac3585** [comment]
The issue is still present for me. I've taken a screenshot showing that radarr has the movie deleted and excluded, however it still shows up in HCT searches. When I try to delete it it just gives me the red "deleting" error. This is the case with some other movies as well. The log snippet I included is for another movie than what is shown in the screenshot, but with the same issue.

[https://i.imgur.com/XvIsmQX.png](https://i.imgur.com/XvIsmQX.png)

[https://pastebin.com/9ruuenz8](https://pastebin.com/9ruuenz8)

I should probably note that it seems that docker is storing my HCT settings somewhere because even after deleting the image and container the IP, radarr API and omdb API are still in the HCT settings page. So perhaps it's also storing the old deleted movie that errored out from a previous build somehow? I'm new to docker so I don't know if this behavior is normal. I use this to install the image:

`docker run -d --name HCT -p 12400:12400 -v /path/to/db:/usr/src/app/db --restart unless-stopped lulu45/home-cinema-toolkit:latest`

**Comment by luluhoc** [comment]
I will investigate tomorrow.

**Comment by luluhoc** [comment]
Can you try the new version when it will build on docker it is a 1.1 version? I changed several things and I have added Clear DB button in setting.

![image](https://user-images.githubusercontent.com/22813220/102384518-20702c80-3fcd-11eb-8925-6ea656380446.png)

**Comment by luluhoc** [comment]
Go ahead. Please let me know if you saw any more bugs and if deleting works properly. Thanks

**Comment by luluhoc** [comment]
I guess it works I'm closing the issue for now if you will have a problem please open a new issue.
