### ISSUE TITLE
Error in Docker log "TypeError: Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by triksmelb** [luluhoc/home-cinema-toolkit#12]
Hi,

just installed v1.1 onto Synology Docker but seeing error in Docker logs:

_**TypeError: Cannot read property 'replace' of undefined**
    at func (/usr/src/app/server/routes/api/v1/rating.js:179:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/src/app/server/routes/api/v1/rating.js:191:9_

Results are sent to frontend so Is this something that can be ignored?
thanks

docker run -d \
  --name HCT \
  -p 12400:12400 \
  -v /volume1/docker/radarr/:/usr/src/app/db \
  --restart unless-stopped \
  lulu45/home-cinema-toolkit:latest

LOG:

yarn run v1.22.5
$ nodemon start.js --prefix server --ignore db/
[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node start.js --prefix server`
Home Cinema Toolkit has started on 12400!
Got movies from radarr...
Searching movies in OMDB...
DB LENGTH 1833
Got movies from radarr...
Searching movies in OMDB...
DB LENGTH 1833
**TypeError: Cannot read property 'replace' of undefined**
    at func (/usr/src/app/server/routes/api/v1/rating.js:179:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/src/app/server/routes/api/v1/rating.js:191:9
Sending movies to Frontend`

**Comment by luluhoc** [comment]
I pushed a new version can you try it? Please wait for docker hub to build.

**Comment by luluhoc** [comment]
Please star the repo if you find it useful

**Comment by triksmelb** [comment]
thank you, updated and cleared db. 
Successfully deleted movies.
