### ISSUE TITLE
Does it support Docker installed on Windows 10?

### ISSUE THREAD

**Issue by ahmetsamsa** [luluhoc/home-cinema-toolkit#2]
Does this tool support docker installed on Windows 10?

**Comment by luluhoc** [comment]
Yes

**Comment by ahmetsamsa** [comment]
![image](https://user-images.githubusercontent.com/36507696/91670870-28918280-eb2a-11ea-99c5-c1169a3b117d.png)
In that case, http://localhost:12400/ is not accessible.
What I'm doing wrong?

**Comment by luluhoc** [comment]
> ![image](https://user-images.githubusercontent.com/36507696/91670870-28918280-eb2a-11ea-99c5-c1169a3b117d.png)
> 
> In that case, http://localhost:12400/ is not accessible.
> 
> What I'm doing wrong? @luluhoc 

Try to install new version
