### ISSUE TITLE
Cannot add scheduled task

### ISSUE THREAD

**Issue by drsood** [luluhoc/home-cinema-toolkit#248]
I am running home cinema toolkit under docker on windows 11 64 bit.
I am unable to add generate a scheduled task after click "save job".

```
yarn run v1.22.5
$ nodemon start.js --prefix server --ignore db/
[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node start.js --prefix server`
Home Cinema Toolkit has started on 12400!
{
  time: { hour: 7, minute: 0, dayOfWeek: null },
  jobType: 'rating',
  addExclusion: true,
  deleteFiles: false,
  variable: '7'
}
```

On restarting home cinema toolkit, i get this error
```
TypeError: Cannot read property 'on' of undefined
    at Function.scheduleJob (/usr/src/app/server/workers/worker.js:41:17)
    at MessagePort.<anonymous> (/usr/src/app/server/node_modules/workerpool/src/worker.js:121:27)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:353:41)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
```

And jobs.json just shows this
`{
  "jobs": []
}
`

Please help

**Comment by luluhoc** [comment]
can you check it out now?

**Comment by drsood** [comment]
I just tested. Its still creating the same jobs.json

Just to let you know, I ran this command
`docker run -d --name HomeCinemaToolkit -e "TZ=Asia/Kolkata" -p 12400:12400 -v "D:\Software\Docker\HomeCinemaToolkit:/usr/src/app/db" --restart unless-stopped lulu45/home-cinema-toolkit:latest` for setting up the container

If I dont use a custom config directory (without the -v part), the job file is created successfully.

**Comment by luluhoc** [comment]
> I just tested. Its still creating the same jobs.json
> 
> Just to let you know, I ran this command `docker run -d --name HomeCinemaToolkit -e "TZ=Asia/Kolkata" -p 12400:12400 -v "D:\Software\Docker\HomeCinemaToolkit:/usr/src/app/db" --restart unless-stopped lulu45/home-cinema-toolkit:latest` for setting up the container
> 
> If I dont use a custom config directory (without the -v part), the job file is created successfully.

it should be good now i pushed it to docker as well

**Comment by drsood** [comment]
Its working as expected. Thank you
