### ISSUE TITLE
Error with docker on unRAID

### ISSUE THREAD

**Issue by djkotik** [luluhoc/home-cinema-toolkit#295]
Hi I have installed however I cannot seem to get it to run. I get the error: standard_init_linux.go:219: exec user process caused: exec format error. Any ideas?

**Comment by bsaurusrex** [comment]
standard_init_linux.go:228: exec user process caused: exec format error

same with truenas docker sadly.

**Comment by luluhoc** [comment]
I will check this error out, i was able to reproduce it

**Comment by luluhoc** [comment]
the issue is resolved just pull the latest image
