### ISSUE TITLE
Sorry, author, I want to contact you

### ISSUE THREAD

**Issue by gdszps** [luluhoc/home-cinema-toolkit#301]
My English is not very good, but I would like to know how to contact you, I have a project and I want to pay you a satisfactory salary to help me complete it.
my email:gdszps@gmail.com

**Comment by gdszps** [comment]
If I get your contact, I will ask for a translator to communicate and cooperate.

**Comment by luluhoc** [comment]
Hey, do you still looking for help? I just sent you an email.
