### ISSUE TITLE
Timeout on V3 and V2

### ISSUE THREAD

**Issue by crwblyth** [luluhoc/home-cinema-toolkit#6]
Finding I get a timeout regardless of entered settings. I have a paid OMDB API key and have tried both V3 and V2 Radarr.

Error is "ETIMEDOUT" briefly in bottom right

**Comment by luluhoc** [comment]
Can you give me console log from docker container?

**Comment by crwblyth** [comment]
`      buffered: [],


      bufferedIndex: 0,


      allBuffers: true,


      allNoop: true,


      pendingcb: 0,


      prefinished: false,


      errorEmitted: false,


      emitClose: true,


      autoDestroy: true,


      errored: null,


      closed: false


    },


    _events: [Object: null prototype] {


      response: [Function: handleResponse],


      error: [Function: handleRequestError]


    },


    _eventsCount: 2,


    _maxListeners: undefined,


    _options: {


      maxRedirects: 21,


      maxBodyLength: 10485760,


      protocol: 'https:',


      path: '/api/movie',


      method: 'GET',


      headers: [Object],


      agent: undefined,


      agents: [Object],


      auth: undefined,


      hostname: 'radarr.domain.com',


      port: null,


      nativeProtocols: [Object],


      pathname: '/api/movie'


    },


    _ended: true,


    _ending: true,


    _redirectCount: 0,


    _redirects: [],


    _requestBodyLength: 0,


    _requestBodyBuffers: [],


    _onNativeResponse: [Function (anonymous)],


    _currentRequest: ClientRequest {


      _events: [Object: null prototype],


      _eventsCount: 7,


      _maxListeners: undefined,


      outputData: [],


      outputSize: 0,


      writable: true,


      destroyed: false,


      _last: true,


      chunkedEncoding: false,


      shouldKeepAlive: false,


      useChunkedEncodingByDefault: false,


      sendDate: false,


      _removedConnection: false,


      _removedContLen: false,


      _removedTE: false,


      _contentLength: 0,


      _hasBody: true,


      _trailer: '',


      finished: true,


      _headerSent: true,


      socket: [TLSSocket],


      _header: 'GET /api/movie HTTP/1.1\r\n' +


        'Accept: application/json, text/plain, */*\r\n' +


        'User-Agent: request\r\n' +


        'X-Api-Key: 0487e98a983241938c1895d8a84bc004\r\n' +


        'Host: radarr.domain.com\r\n' +


        'Connection: close\r\n' +


        '\r\n',


      _keepAliveTimeout: 0,


      _onPendingData: [Function: noopPendingOutput],


      agent: [Agent],


      socketPath: undefined,


      method: 'GET',


      maxHeaderSize: undefined,


      insecureHTTPParser: undefined,


      path: '/api/movie',


      _ended: false,


      res: null,


      aborted: false,


      timeoutCb: null,


      upgradeOrConnect: false,


      parser: null,


      maxHeadersCount: null,


      reusedSocket: false,


      host: 'radarr.domain.com',


      protocol: 'https:',


      _redirectable: [Circular *1],


      [Symbol(kCapture)]: false,


      [Symbol(kNeedDrain)]: false,


      [Symbol(corked)]: 0,


      [Symbol(kOutHeaders)]: [Object: null prototype]


    },


    _currentUrl: 'https://radarr.domain.com/api/movie',


    [Symbol(kCapture)]: false


  },


  response: undefined,


  isAxiosError: true,


  toJSON: [Function: toJSON]


}`

**Comment by luluhoc** [comment]
it looks like the URL to radarr is wrong, please set the URL as IP. If you have radarr in host consider it that it won't work in docker container

**Comment by crwblyth** [comment]
> 
> 
> it looks like the URL to radarr is wrong, please set the URL as IP. If you have radarr in host consider it that it won't work in docker container

Working with IP. 

Thank you.
